spring.application.name=RestauranteMili
#CONE A MYSQL
spring.datasource.url=
spring.datasource.username=root
spring.activemq.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#PUERTO
server.port=8080